import React from 'react';

const { useState } = React;

/**
 * Poll data structure
 */
interface PollData {
    question: string;
    options: string[];
    allowMultiple?: boolean;
    description?: string;
}

/**
 * Props for the PollWidget component
 */
interface PollWidgetProps {
    /**
     * The poll data as a JSON string (from the code block content)
     */
    data: string;
}

/**
 * Interactive poll widget component
 *
 * This widget renders polls generated by the poll-generator skill.
 * It displays the question, options, and allows users to select answers.
 */
export default function PollWidget({ data }: PollWidgetProps) {
    const [selected, setSelected] = useState<Set<number>>(new Set());
    const [showResults, setShowResults] = useState(false);
    const [votes, setVotes] = useState<Record<number, number>>({});

    // Parse the poll data
    let poll: PollData;
    try {
        poll = JSON.parse(data);
    } catch (error) {
        return (
            <div className="border border-destructive bg-destructive/10 rounded-lg p-4">
                <p className="text-destructive font-medium">Error: Invalid poll data</p>
                <p className="text-sm text-muted mt-2">Failed to parse poll JSON</p>
            </div>
        );
    }

    // Validate poll structure
    if (!poll.question || !Array.isArray(poll.options) || poll.options.length < 2) {
        return (
            <div className="border border-destructive bg-destructive/10 rounded-lg p-4">
                <p className="text-destructive font-medium">Error: Invalid poll structure</p>
                <p className="text-sm text-muted mt-2">
                    Poll must have a question and at least 2 options
                </p>
            </div>
        );
    }

    const handleOptionClick = (index: number) => {
        if (showResults) return;

        const newSelected = new Set(selected);

        if (poll.allowMultiple) {
            // Multi-select: toggle the option
            if (newSelected.has(index)) {
                newSelected.delete(index);
            } else {
                newSelected.add(index);
            }
        } else {
            // Single select: replace the selection
            newSelected.clear();
            newSelected.add(index);
        }

        setSelected(newSelected);
    };

    const handleSubmit = () => {
        if (selected.size === 0) return;

        // Update vote counts (simulated - in real app this would be persisted)
        const newVotes = { ...votes };
        selected.forEach(index => {
            newVotes[index] = (newVotes[index] || 0) + 1;
        });
        setVotes(newVotes);
        setShowResults(true);
    };

    const handleReset = () => {
        setSelected(new Set());
        setShowResults(false);
    };

    const totalVotes = Object.values(votes).reduce((sum, count) => sum + count, 0);

    const getPercentage = (index: number): number => {
        if (totalVotes === 0) return 0;
        return ((votes[index] || 0) / totalVotes) * 100;
    };

    return (
        <div className="border border-mixer-5 bg-mixer-1 rounded-lg p-6 max-w-2xl">
            {/* Question */}
            <h3 className="text-lg font-semibold mb-2">{poll.question}</h3>

            {/* Description */}
            {poll.description && (
                <p className="text-sm text-muted mb-4">{poll.description}</p>
            )}

            {/* Multi-select indicator */}
            {poll.allowMultiple && !showResults && (
                <p className="text-xs text-info mb-3">
                    ℹ️ You can select multiple options
                </p>
            )}

            {/* Options */}
            <div className="space-y-2 mb-4">
                {poll.options.map((option, index) => {
                    const isSelected = selected.has(index);
                    const percentage = getPercentage(index);

                    return (
                        <div
                            key={index}
                            onClick={() => handleOptionClick(index)}
                            className={`
                                relative border rounded-lg p-3 cursor-pointer transition-all
                                ${showResults
                                    ? 'cursor-default'
                                    : 'hover:border-mixer-10 hover:bg-mixer-2'
                                }
                                ${isSelected && !showResults
                                    ? 'border-info bg-info/10'
                                    : 'border-mixer-5'
                                }
                            `}
                        >
                            <div className="flex items-center justify-between relative z-10">
                                <div className="flex items-center gap-3">
                                    {/* Checkbox/Radio indicator */}
                                    {!showResults && (
                                        <div className={`
                                            w-5 h-5 border-2 flex items-center justify-center
                                            ${poll.allowMultiple ? 'rounded' : 'rounded-full'}
                                            ${isSelected
                                                ? 'border-info bg-info'
                                                : 'border-mixer-10'
                                            }
                                        `}>
                                            {isSelected && (
                                                <span className="text-white text-xs">✓</span>
                                            )}
                                        </div>
                                    )}
                                    <span className="font-medium">{option}</span>
                                </div>

                                {/* Results */}
                                {showResults && (
                                    <div className="text-sm font-medium">
                                        {votes[index] || 0} vote{votes[index] !== 1 ? 's' : ''}
                                        <span className="text-muted ml-2">
                                            ({percentage.toFixed(1)}%)
                                        </span>
                                    </div>
                                )}
                            </div>

                            {/* Results bar */}
                            {showResults && (
                                <div
                                    className="absolute inset-0 bg-success/20 rounded-lg transition-all"
                                    style={{ width: `${percentage}%` }}
                                />
                            )}
                        </div>
                    );
                })}
            </div>

            {/* Actions */}
            <div className="flex gap-2">
                {!showResults ? (
                    <>
                        <button
                            onClick={handleSubmit}
                            disabled={selected.size === 0}
                            className={`
                                px-4 py-2 rounded-lg font-medium transition-all
                                ${selected.size > 0
                                    ? 'bg-info text-white hover:bg-info/90'
                                    : 'bg-mixer-3 text-muted cursor-not-allowed'
                                }
                            `}
                        >
                            Submit Vote
                        </button>
                        {selected.size > 0 && (
                            <button
                                onClick={() => setSelected(new Set())}
                                className="px-4 py-2 rounded-lg font-medium border border-mixer-5 hover:bg-mixer-2 transition-all"
                            >
                                Clear
                            </button>
                        )}
                    </>
                ) : (
                    <button
                        onClick={handleReset}
                        className="px-4 py-2 rounded-lg font-medium border border-mixer-5 hover:bg-mixer-2 transition-all"
                    >
                        Vote Again
                    </button>
                )}
            </div>

            {/* Total votes */}
            {showResults && totalVotes > 0 && (
                <p className="text-sm text-muted mt-4">
                    Total votes: {totalVotes}
                </p>
            )}
        </div>
    );
}
