packages:
  - llumiverse/common
  - packages/*
  - templates/*
  - "!templates/worker-template"
minimumReleaseAge: 4320 # 3 days in minutes, minimumReleaseAge protects against supply chain attacks.
minimumReleaseAgeExclude:
  - '@vertesia/*'
  - '@llumiverse/*'
  - 'hono@4.12.14'