packages:
  - llumiverse/common
  - packages/*
  - templates/*
  - "!templates/worker-template"
minimumReleaseAge: 1440 # 1 day in minutes, minimumReleaseAge protects against supply chain attacks.
minimumReleaseAgeExclude:
  - '@vertesia/*'
  - '@llumiverse/*'
  # Renovate security update: lodash-es@4.18.1
  - lodash-es@4.18.1
