/**
 * Tests for serverless canvas rendering
 */

import { describe, it, expect } from 'vitest';
import { renderToBuffer, renderToBase64, renderToDataUrl } from '../src/render/serverlessRender.js';
import type { FragmentTemplate } from '../src/types.js';

describe('serverless canvas rendering', () => {
  const template: FragmentTemplate = {
    title: 'Fund Parameters',
    sections: [
      {
        title: 'Identity',
        layout: 'grid-3',
        fields: [
          { label: 'Firm Name', key: 'firmName' },
          { label: 'Fund Name', key: 'fundName' },
          { label: 'Vintage', key: 'vintageYear', format: 'number' },
        ],
      },
      {
        title: 'Financials',
        layout: 'grid-2',
        fields: [
          { label: 'Target Size', key: 'targetSize', format: 'currency', currency: 'USD' },
          { label: 'IRR Target', key: 'irrTarget', format: 'percent' },
        ],
      },
    ],
    footer: 'Generated by Fusion UX',
  };

  const data = {
    firmName: 'Acme Capital',
    fundName: 'Acme Fund IV',
    vintageYear: 2024,
    targetSize: 500000000,
    irrTarget: 0.25,
  };

  describe('renderToBuffer', () => {
    it('renders a template to PNG buffer', () => {
      const buffer = renderToBuffer(template, data);

      expect(buffer).toBeInstanceOf(Buffer);
      expect(buffer.length).toBeGreaterThan(0);

      // Verify PNG magic bytes
      expect(buffer[0]).toBe(0x89);
      expect(buffer[1]).toBe(0x50); // P
      expect(buffer[2]).toBe(0x4e); // N
      expect(buffer[3]).toBe(0x47); // G
    });

    it('renders with custom width', () => {
      const narrowBuffer = renderToBuffer(template, data, { width: 400 });
      const wideBuffer = renderToBuffer(template, data, { width: 800 });

      // Both should be valid PNGs
      expect(narrowBuffer[0]).toBe(0x89);
      expect(wideBuffer[0]).toBe(0x89);
    });

    it('handles missing data gracefully', () => {
      const partialData = { firmName: 'Test' };
      const buffer = renderToBuffer(template, partialData);

      expect(buffer).toBeInstanceOf(Buffer);
      expect(buffer.length).toBeGreaterThan(0);
    });

    it('handles null/undefined values', () => {
      const dataWithNulls = {
        firmName: null,
        fundName: undefined,
        vintageYear: 2024,
      };

      const buffer = renderToBuffer(template, dataWithNulls as Record<string, unknown>);
      expect(buffer).toBeInstanceOf(Buffer);
    });

    it('renders different layouts', () => {
      const templates: FragmentTemplate[] = [
        {
          sections: [{ title: 'Grid 2', layout: 'grid-2', fields: [{ label: 'A', key: 'firmName' }] }],
        },
        {
          sections: [{ title: 'Grid 3', layout: 'grid-3', fields: [{ label: 'A', key: 'firmName' }] }],
        },
        {
          sections: [{ title: 'Grid 4', layout: 'grid-4', fields: [{ label: 'A', key: 'firmName' }] }],
        },
        {
          sections: [{ title: 'List', layout: 'list', fields: [{ label: 'A', key: 'firmName' }] }],
        },
      ];

      for (const t of templates) {
        const buffer = renderToBuffer(t, data);
        expect(buffer).toBeInstanceOf(Buffer);
        expect(buffer[0]).toBe(0x89); // PNG
      }
    });
  });

  describe('renderToBase64', () => {
    it('renders to base64 string', () => {
      const base64 = renderToBase64(template, data);

      expect(typeof base64).toBe('string');
      expect(base64.length).toBeGreaterThan(0);

      // Verify it's valid base64
      const buffer = Buffer.from(base64, 'base64');
      expect(buffer[0]).toBe(0x89); // PNG magic byte
    });
  });

  describe('renderToDataUrl', () => {
    it('renders to data URL', () => {
      const dataUrl = renderToDataUrl(template, data);

      expect(dataUrl).toMatch(/^data:image\/png;base64,/);

      // Extract and verify base64
      const base64 = dataUrl.replace('data:image/png;base64,', '');
      const buffer = Buffer.from(base64, 'base64');
      expect(buffer[0]).toBe(0x89);
    });
  });

  describe('value formatting', () => {
    it('formats currency values', () => {
      const currencyTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'Test',
            fields: [{ label: 'Amount', key: 'amount', format: 'currency', currency: 'EUR' }],
          },
        ],
      };

      const buffer = renderToBuffer(currencyTemplate, { amount: 1234567 });
      expect(buffer).toBeInstanceOf(Buffer);
    });

    it('formats percent values', () => {
      const percentTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'Test',
            fields: [
              { label: 'Rate (decimal)', key: 'rateDecimal', format: 'percent' },
              { label: 'Rate (whole)', key: 'rateWhole', format: 'percent' },
            ],
          },
        ],
      };

      const buffer = renderToBuffer(percentTemplate, {
        rateDecimal: 0.15, // Should render as 15%
        rateWhole: 25, // Should render as 25%
      });
      expect(buffer).toBeInstanceOf(Buffer);
    });

    it('formats date values', () => {
      const dateTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'Test',
            fields: [{ label: 'Date', key: 'date', format: 'date' }],
          },
        ],
      };

      const buffer = renderToBuffer(dateTemplate, { date: '2024-06-15' });
      expect(buffer).toBeInstanceOf(Buffer);
    });

    it('formats boolean values', () => {
      const boolTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'Test',
            fields: [
              { label: 'Active', key: 'active', format: 'boolean' },
              { label: 'Closed', key: 'closed', format: 'boolean' },
            ],
          },
        ],
      };

      const buffer = renderToBuffer(boolTemplate, { active: true, closed: false });
      expect(buffer).toBeInstanceOf(Buffer);
    });
  });

  describe('highlight colors', () => {
    it('renders with different highlight colors', () => {
      const highlightTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'Status',
            layout: 'grid-4',
            fields: [
              { label: 'Success', key: 'a', highlight: 'success' },
              { label: 'Warning', key: 'b', highlight: 'warning' },
              { label: 'Error', key: 'c', highlight: 'error' },
              { label: 'Info', key: 'd', highlight: 'info' },
            ],
          },
        ],
      };

      const buffer = renderToBuffer(highlightTemplate, {
        a: 'Good',
        b: 'Caution',
        c: 'Bad',
        d: 'Note',
      });

      expect(buffer).toBeInstanceOf(Buffer);
      expect(buffer.length).toBeGreaterThan(0);
    });
  });

  describe('edge cases', () => {
    it('handles empty sections', () => {
      const emptyTemplate: FragmentTemplate = {
        title: 'Empty',
        sections: [],
      };

      const buffer = renderToBuffer(emptyTemplate, {});
      expect(buffer).toBeInstanceOf(Buffer);
    });

    it('handles very long text values', () => {
      const longTextTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'Long Text',
            fields: [{ label: 'Description', key: 'desc' }],
          },
        ],
      };

      const buffer = renderToBuffer(longTextTemplate, {
        desc: 'A'.repeat(200),
      });
      expect(buffer).toBeInstanceOf(Buffer);
    });

    it('handles special characters', () => {
      const specialTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'Special Chars',
            fields: [{ label: 'Name', key: 'name' }],
          },
        ],
      };

      const buffer = renderToBuffer(specialTemplate, {
        name: 'Test & Co. <>"\'',
      });
      expect(buffer).toBeInstanceOf(Buffer);
    });

    it('handles units', () => {
      const unitTemplate: FragmentTemplate = {
        sections: [
          {
            title: 'With Units',
            fields: [
              { label: 'Duration', key: 'duration', format: 'number', unit: 'years' },
              { label: 'Rate', key: 'rate', format: 'percent', unit: 'p.a.' },
            ],
          },
        ],
      };

      const buffer = renderToBuffer(unitTemplate, {
        duration: 5,
        rate: 8.5,
      });
      expect(buffer).toBeInstanceOf(Buffer);
    });
  });
});
