import { activityInfo, log } from "@temporalio/activity";
import { ApplicationFailure } from "@temporalio/workflow";
import { VertesiaClient } from "@vertesia/client";
import { NodeStreamSource } from "@vertesia/client/node";
import { basename } from "path";
import { Readable } from "stream";
import mime from "mime";
import { fetchBlobAsBuffer } from "../utils/blobs.js";


export const agentStoragePath = (runId: string) => `agents/${runId}`;

/**
 *
 * Save an artifact generated by an agent to cloud storage
 *
 * @param client
 * @param name
 * @param fileContent
 * @param mimeType
 * @returns
 */
export async function saveAgentArtifact(
    client: VertesiaClient,
    name: string,
    fileContent: Readable,
    mimeType: string = "application/json",
    storageId?: string,
) {
    const id = storageId || activityInfo().workflowExecution.runId;
    const ext = mime.getExtension(mimeType);
    if (!name) {
        throw ApplicationFailure.nonRetryable(`Name is required`);
    }

    //create the file path and append extension if needed
    const filePath = agentStoragePath(id) + "/" + name + (ext && !name.endsWith(ext) ? "." + ext : "");

    try {
        const source = new NodeStreamSource(fileContent, `${id}-${basename(filePath)}`, mimeType, filePath);
        return await client.files.uploadFile(source);
    } catch (err: any) {
        log.error(`Failed to save agent artifact for run ${id}`, {
            err,
            file: filePath,
        });
        throw ApplicationFailure.nonRetryable(
            `Failed to save agent artifact for run ${id}`,
            "SaveAgentArtifactError",
            {
                error: err,
            },
        );
    }
}

export async function fetchAgentArtifact(client: VertesiaClient, name: string, storageId?: string) {
    const id = storageId || activityInfo().workflowExecution.runId;
    const filePath = agentStoragePath(id) + "/" + name;
    return fetchBlobAsBuffer(client, filePath);
}
