import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

type ServerResource = 'activities' | 'interactions' | 'processes' | 'skills' | 'templates' | 'tools' | 'types';

interface ScaffoldContext {
    modules?: string[];
    answers?: Record<string, unknown>;
    cleanup?: boolean;
}

interface ModuleDefinition {
    virtual?: boolean;
    requires?: string[];
    ui?: {
        entry?: string;
        routes?: string;
        provider?: string;
    };
    resources?: string;
    packageScripts?: Record<string, string>;
}

interface TemplateConfig {
    modules?: Record<string, ModuleDefinition>;
}

interface ResolvedModule {
    name: string;
    definition: ModuleDefinition;
}

const SERVER_RESOURCES: ServerResource[] = [
    'activities',
    'interactions',
    'processes',
    'skills',
    'templates',
    'tools',
    'types',
];
const BASE_MODULE = 'app';
const GENERATED_FILE_HEADER =
    '// This file is generated by the plugin template codegen. Modify it only if you know what you are doing.\n';
const TEMPLATE_ONLY_PACKAGE_SCRIPTS = ['codegen:dev', 'test:codegen'];
const MAX_COMPACT_EXPORT_LENGTH = 120;

function readJson<T>(filePath: string): T {
    return JSON.parse(fs.readFileSync(filePath, 'utf8')) as T;
}

function parseArgs(argv: string[]): { context: string } {
    const contextIndex = argv.indexOf('--context');
    if (contextIndex < 0 || !argv[contextIndex + 1]) {
        throw new Error('Usage: node scripts/dist/codegen.js --context <context-json>');
    }
    return { context: argv[contextIndex + 1] };
}

function loadConfig(projectRoot: string): TemplateConfig {
    return readJson<TemplateConfig>(path.join(projectRoot, 'template.config.json'));
}

function loadContext(projectRoot: string, contextFile: string): ScaffoldContext {
    return readJson<ScaffoldContext>(path.resolve(projectRoot, contextFile));
}

function resolveModules(config: TemplateConfig, selectedModules: string[]): ResolvedModule[] {
    const definitions = config.modules;
    if (!definitions) {
        throw new Error('template.config.json does not define any modules');
    }
    const moduleDefinitions = definitions;

    const selected = [BASE_MODULE, ...(selectedModules.length > 0 ? selectedModules : ['default'])];
    const resolved = new Map<string, ResolvedModule>();
    const visiting = new Set<string>();

    function visit(moduleName: string, chain: string[]): void {
        if (resolved.has(moduleName)) return;
        if (visiting.has(moduleName)) {
            throw new Error(`Module dependency cycle detected: ${[...chain, moduleName].join(' -> ')}`);
        }

        const definition = moduleDefinitions[moduleName];
        if (!definition) {
            throw new Error(`Unknown template module: ${moduleName}`);
        }

        visiting.add(moduleName);
        for (const dependency of definition.requires ?? []) {
            visit(dependency, [...chain, moduleName]);
        }
        visiting.delete(moduleName);
        resolved.set(moduleName, { name: moduleName, definition });
    }

    for (const moduleName of selected) {
        visit(moduleName, []);
    }

    return [...resolved.values()];
}

function toImportPath(fromDir: string, targetPath: string): string {
    let relative = path.relative(fromDir, targetPath).replaceAll(path.sep, '/');
    if (!relative.startsWith('.')) {
        relative = `./${relative}`;
    }
    return relative;
}

function varName(prefix: string, moduleName: string): string {
    const normalized = moduleName
        .split(/[^a-zA-Z0-9]+/)
        .filter(Boolean)
        .map((part, index) => {
            const lower = part.toLowerCase();
            return index === 0 ? lower : `${lower[0]?.toUpperCase() ?? ''}${lower.slice(1)}`;
        })
        .join('');
    return `${normalized || 'module'}${prefix}`;
}

function componentVarName(prefix: string, moduleName: string): string {
    const name = varName(prefix, moduleName);
    return `${name[0]?.toUpperCase() ?? ''}${name.slice(1)}`;
}

function writeFile(projectRoot: string, filePath: string, content: string): void {
    const absolutePath = path.join(projectRoot, filePath);
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    fs.writeFileSync(absolutePath, content);
}

function renderArrayExport(name: string, values: string[]): string {
    if (values.length === 0) return `export const ${name} = [];`;

    const compact = `export const ${name} = [${values.join(', ')}];`;
    if (compact.length <= MAX_COMPACT_EXPORT_LENGTH) return compact;

    return `export const ${name} = [\n${values.map((value) => `    ${value},`).join('\n')}\n];`;
}

function generateUiModules(projectRoot: string, modules: ResolvedModule[]): void {
    const uiEntryModules = modules.filter((module) => module.definition.ui?.entry);
    if (uiEntryModules.length > 1) {
        throw new Error(
            `Expected at most one active module with uiEntry, found ${uiEntryModules.length}: ${uiEntryModules
                .map((module) => module.name)
                .join(', ')}`,
        );
    }

    const fromDir = path.join(projectRoot, 'src/ui');
    const imports: string[] = [];
    const entryImports: string[] = [];
    const routeVars: string[] = [];
    const providerVars: string[] = [];

    const uiEntry = uiEntryModules[0]?.definition.ui?.entry;
    const uiEntryImport = uiEntry ? toImportPath(fromDir, path.join(projectRoot, uiEntry)) : './shell/AppEntry';
    entryImports.push(`export { AppEntry } from '${uiEntryImport}';`);

    for (const module of modules) {
        if (module.definition.ui?.routes) {
            const name = varName('Routes', module.name);
            routeVars.push(name);
            imports.push(
                `import { routes as ${name} } from '${toImportPath(
                    fromDir,
                    path.join(projectRoot, module.definition.ui.routes),
                )}';`,
            );
        }
        if (module.definition.ui?.provider) {
            const name = componentVarName('Providers', module.name);
            providerVars.push(name);
            imports.push(
                `import { AppProviders as ${name} } from '${toImportPath(
                    fromDir,
                    path.join(projectRoot, module.definition.ui.provider),
                )}';`,
            );
        }
    }

    const providers = `export const providers = [${providerVars.join(', ')}];`;

    writeFile(
        projectRoot,
        'src/ui/app-ui-modules.tsx',
        `${GENERATED_FILE_HEADER}\n${imports
            .sort((left, right) => {
                const leftModule = left.match(/from '([^']+)'/)?.[1] ?? left;
                const rightModule = right.match(/from '([^']+)'/)?.[1] ?? right;
                return leftModule.localeCompare(rightModule) || left.localeCompare(right);
            })
            .join('\n')}\n\n${renderArrayExport(
            'routes',
            routeVars.map((name) => `...${name}`),
        )}\n\n${providers}\n`,
    );
    writeFile(projectRoot, 'src/ui/app-ui-entry.tsx', `${GENERATED_FILE_HEADER}${entryImports.join('\n')}\n`);
}

function syncPackageScripts(projectRoot: string, config: TemplateConfig, modules: ResolvedModule[]): void {
    const packageJsonPath = path.join(projectRoot, 'package.json');
    if (!fs.existsSync(packageJsonPath)) return;

    const packageJson = readJson<{ scripts?: Record<string, string> } & Record<string, unknown>>(packageJsonPath);
    const moduleScriptNames = new Set(
        Object.values(config.modules ?? {}).flatMap((module) => Object.keys(module.packageScripts ?? {})),
    );
    const activeScripts = Object.assign(
        {},
        ...modules.map((module) => module.definition.packageScripts ?? {}),
    ) as Record<string, string>;

    const scripts = { ...packageJson.scripts };
    for (const scriptName of moduleScriptNames) {
        delete scripts[scriptName];
    }
    packageJson.scripts = {
        ...scripts,
        ...activeScripts,
    };
    fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 4)}\n`);
}

function cleanupPackageScripts(projectRoot: string): void {
    const packageJsonPath = path.join(projectRoot, 'package.json');
    if (!fs.existsSync(packageJsonPath)) return;

    const packageJson = readJson<{ scripts?: Record<string, string> } & Record<string, unknown>>(packageJsonPath);
    if (!packageJson.scripts) return;

    let changed = false;
    for (const scriptName of TEMPLATE_ONLY_PACKAGE_SCRIPTS) {
        if (scriptName in packageJson.scripts) {
            delete packageJson.scripts[scriptName];
            changed = true;
        }
    }
    if (changed) {
        fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 4)}\n`);
    }
}

function generateServerModules(projectRoot: string, modules: ResolvedModule[]): void {
    const fromDir = path.join(projectRoot, 'src/tool-server');
    const imports: string[] = [];
    const resources = new Map<ServerResource, string[]>();
    for (const resource of SERVER_RESOURCES) {
        resources.set(resource, []);
    }

    function resourceRefs(resource: ServerResource): string[] {
        const refs = resources.get(resource);
        if (!refs) throw new Error(`Unknown server resource: ${resource}`);
        return refs;
    }

    for (const module of modules) {
        const modulePath = module.definition.resources;
        if (!modulePath) continue;

        const moduleVar = varName('Resources', module.name);
        imports.push(
            `import * as ${moduleVar} from '${toImportPath(fromDir, path.join(projectRoot, modulePath, 'index'))}.js';`,
        );

        for (const resource of SERVER_RESOURCES) {
            resourceRefs(resource).push(`${moduleVar}.${resource}`);
        }
    }

    const exports = SERVER_RESOURCES.map((resource) => {
        const names = resourceRefs(resource);
        return renderArrayExport(
            resource,
            names.map((name) => `...${name}`),
        );
    });

    writeFile(
        projectRoot,
        'src/tool-server/app-server-modules.ts',
        `${GENERATED_FILE_HEADER}${imports.sort().join('\n')}\n\n${exports.join('\n')}\n`,
    );
}

function cleanupInactiveModules(projectRoot: string, modules: ResolvedModule[]): void {
    const active = new Set(modules.filter((module) => !module.definition.virtual).map((module) => module.name));
    const modulesDir = path.join(projectRoot, 'src/modules');
    if (!fs.existsSync(modulesDir)) return;

    for (const entry of fs.readdirSync(modulesDir, { withFileTypes: true })) {
        if (entry.isDirectory() && !active.has(entry.name)) {
            fs.rmSync(path.join(modulesDir, entry.name), { recursive: true, force: true });
        }
    }
}

function main(): void {
    const projectRoot = process.cwd();
    const { context: contextFile } = parseArgs(process.argv.slice(2));
    const config = loadConfig(projectRoot);
    const context = loadContext(projectRoot, contextFile);
    const modules = resolveModules(config, context.modules ?? ['default']);
    const shouldCleanup = context.cleanup !== false;

    generateUiModules(projectRoot, modules);
    generateServerModules(projectRoot, modules);
    syncPackageScripts(projectRoot, config, modules);
    if (shouldCleanup) {
        cleanupPackageScripts(projectRoot);
        cleanupInactiveModules(projectRoot, modules);
    }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    main();
}
