// This file is generated by the plugin template codegen. Modify it only if you know what you are doing.
import * as appResources from '../modules/app/resources/index.js';
import * as contentAppResources from '../modules/content-app/resources/index.js';
import * as examplesResources from '../modules/examples/resources/index.js';

export const activities = [
    ...appResources.activities,
    ...examplesResources.activities,
    ...contentAppResources.activities,
];
export const dashboards = [
    ...appResources.dashboards,
    ...examplesResources.dashboards,
    ...contentAppResources.dashboards,
];
export const interactions = [
    ...appResources.interactions,
    ...examplesResources.interactions,
    ...contentAppResources.interactions,
];
export const processes = [...appResources.processes, ...examplesResources.processes, ...contentAppResources.processes];
export const skills = [...appResources.skills, ...examplesResources.skills, ...contentAppResources.skills];
export const templates = [...appResources.templates, ...examplesResources.templates, ...contentAppResources.templates];
export const tools = [...appResources.tools, ...examplesResources.tools, ...contentAppResources.tools];
export const types = [...appResources.types, ...examplesResources.types, ...contentAppResources.types];
