import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const testDir = path.dirname(fileURLToPath(import.meta.url));
const templateRoot = path.resolve(testDir, '../..');
const codegenScript = path.join(templateRoot, 'codegen/dist/codegen.js');
const generatedFiles = [
    'src/ui/app-ui-entry.tsx',
    'src/ui/app-ui-modules.tsx',
    'src/tool-server/app-server-modules.ts',
];
const generatedHeader =
    '// This file is generated by the plugin template codegen. Modify it only if you know what you are doing.\n';

function copyTemplateInputs(targetRoot) {
    fs.copyFileSync(path.join(templateRoot, 'template.config.json'), path.join(targetRoot, 'template.config.json'));
    fs.copyFileSync(path.join(templateRoot, 'package.json'), path.join(targetRoot, 'package.json'));
    fs.cpSync(path.join(templateRoot, 'src/modules'), path.join(targetRoot, 'src/modules'), { recursive: true });
}

function runCodegen(tmpRoot, modules) {
    const contextPath = path.join(tmpRoot, '.create-plugin-context.json');
    fs.writeFileSync(contextPath, `${JSON.stringify({ modules }, null, 2)}\n`);

    execFileSync(process.execPath, [codegenScript, '--context', contextPath], {
        cwd: tmpRoot,
        stdio: 'pipe',
    });
}

function writePackageJson(tmpRoot) {
    fs.writeFileSync(
        path.join(tmpRoot, 'package.json'),
        `${JSON.stringify({ name: 'test-plugin', scripts: { build: 'pnpm build' } }, null, 4)}\n`,
    );
}

test('dev module codegen matches checked-in generated files', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['dev']);

        for (const file of generatedFiles) {
            const expected = fs.readFileSync(path.join(templateRoot, file), 'utf8');
            const actual = fs.readFileSync(path.join(tmpRoot, file), 'utf8');
            assert.equal(actual, expected, `${file} should match dev codegen output`);
        }
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('default module codegen keeps only the app module', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['default']);

        const uiModules = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-modules.tsx'), 'utf8');
        const serverModules = fs.readFileSync(path.join(tmpRoot, 'src/tool-server/app-server-modules.ts'), 'utf8');

        assert.match(uiModules, /modules\/app\/ui\/routes/);
        assert.doesNotMatch(uiModules, /modules\/assistant/);
        assert.doesNotMatch(uiModules, /modules\/examples/);
        assert.match(serverModules, /modules\/app\/resources\/index\.js/);
        assert.doesNotMatch(serverModules, /modules\/examples/);
        const packageJson = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'package.json'), 'utf8'));
        assert.equal(packageJson.scripts['codegen:dev'], undefined);
        assert.equal(packageJson.scripts['test:codegen'], undefined);
        assert.equal(packageJson.scripts['seed:content'], undefined);
        assert.equal(packageJson.scripts['exercise:content'], undefined);
        assert.equal(packageJson.scripts['service:quality'], undefined);
        assert.equal(packageJson.scripts['service:build'], undefined);

        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/assistant')), false);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/examples')), false);
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('service module selects service entry and cleans inactive modules', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['appgen', 'assistant']);

        const uiEntry = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-entry.tsx'), 'utf8');
        const uiModules = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-modules.tsx'), 'utf8');
        const serverModules = fs.readFileSync(path.join(tmpRoot, 'src/tool-server/app-server-modules.ts'), 'utf8');
        const packageJson = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'package.json'), 'utf8'));

        assert.equal(uiEntry, `${generatedHeader}export { AppEntry } from '../modules/service/ui/AppEntry';\n`);
        assert.match(uiModules, /modules\/app\/ui\/routes/);
        assert.match(uiModules, /modules\/assistant\/ui\/routes/);
        assert.doesNotMatch(uiModules, /modules\/examples/);
        assert.match(serverModules, /modules\/app\/resources\/index\.js/);
        assert.doesNotMatch(serverModules, /modules\/examples/);
        assert.equal(packageJson.scripts['service:quality'], 'node src/modules/service/scripts/app-quality-check.mjs');
        assert.equal(
            packageJson.scripts['service:build:server'],
            'pnpm run service:quality && node src/modules/service/scripts/build-server-esbuild.mjs && node src/modules/service/scripts/write-app-package.mjs',
        );
        assert.equal(
            packageJson.scripts['service:build:ui'],
            'pnpm run typecheck && vite build --mode app --outDir dist/app --emptyOutDir --minify false',
        );
        assert.equal(
            packageJson.scripts['service:build'],
            'pnpm run service:build:ui && vite build --mode lib && pnpm run service:build:server',
        );

        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/agent')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/assistant')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/service')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/examples')), false);
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('content-app module composes app routes and contributes resources', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        writePackageJson(tmpRoot);
        runCodegen(tmpRoot, ['content-app']);

        const uiModules = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-modules.tsx'), 'utf8');
        const serverModules = fs.readFileSync(path.join(tmpRoot, 'src/tool-server/app-server-modules.ts'), 'utf8');
        const packageJson = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'package.json'), 'utf8'));

        assert.match(uiModules, /modules\/app\/ui\/routes/);
        assert.match(uiModules, /modules\/content-app\/ui\/routes/);
        assert.match(serverModules, /modules\/app\/resources\/index\.js/);
        assert.match(serverModules, /modules\/content-app\/resources\/index\.js/);
        assert.match(serverModules, /export const dashboards = \[/);
        assert.match(serverModules, /export const processes = \[/);
        assert.equal(packageJson.scripts['seed:content'], 'node src/modules/content-app/scripts/seed-content-app.mjs');
        assert.equal(
            packageJson.scripts['exercise:content'],
            'node src/modules/content-app/scripts/exercise-content-app.mjs',
        );

        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/content-app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/assistant')), false);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/examples')), false);
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});
