import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath, pathToFileURL } from 'node:url';

const testDir = path.dirname(fileURLToPath(import.meta.url));
const templateRoot = path.resolve(testDir, '../..');
const codegenScript = path.join(templateRoot, 'codegen/dist/codegen.js');
const generatedFiles = [
    'src/ui/app-ui-entry.tsx',
    'src/ui/app-ui-modules.tsx',
    'src/tool-server/app-server-modules.ts',
];
const generatedHeader =
    '// This file is generated by the plugin template codegen. Modify it only if you know what you are doing.\n';

function copyTemplateInputs(targetRoot) {
    fs.copyFileSync(path.join(templateRoot, 'template.config.json'), path.join(targetRoot, 'template.config.json'));
    fs.copyFileSync(path.join(templateRoot, 'package.json'), path.join(targetRoot, 'package.json'));
    fs.cpSync(path.join(templateRoot, 'src/modules'), path.join(targetRoot, 'src/modules'), { recursive: true });
    fs.cpSync(path.join(templateRoot, 'tests'), path.join(targetRoot, 'tests'), { recursive: true });
}

function runCodegen(tmpRoot, modules) {
    const contextPath = path.join(tmpRoot, '.create-plugin-context.json');
    fs.writeFileSync(contextPath, `${JSON.stringify({ modules }, null, 2)}\n`);

    execFileSync(process.execPath, [codegenScript, '--context', contextPath], {
        cwd: tmpRoot,
        stdio: 'pipe',
    });
}

function writePackageJson(tmpRoot) {
    fs.writeFileSync(
        path.join(tmpRoot, 'package.json'),
        `${JSON.stringify({ name: 'test-plugin', scripts: { build: 'pnpm build' } }, null, 4)}\n`,
    );
}

function writeDurableTestFixtures(tmpRoot) {
    const unitPath = path.join(tmpRoot, 'src/modules/app/resources/app-contract.test.ts');
    const e2ePath = path.join(tmpRoot, 'tests/e2e/app.spec.ts');
    const fixturePath = path.join(tmpRoot, 'tests/e2e/vertesia.ts');
    fs.mkdirSync(path.dirname(unitPath), { recursive: true });
    fs.mkdirSync(path.dirname(e2ePath), { recursive: true });
    fs.writeFileSync(
        unitPath,
        "import { expect, test } from 'vitest';\ntest('app contract', () => expect(true).toBe(true));\n",
    );
    fs.writeFileSync(
        e2ePath,
        "import { expect, test } from './vertesia';\ntest('primary flow', async ({ page }) => { await page.goto('/'); await expect(page.locator('body')).toBeVisible(); });\n",
    );
    fs.writeFileSync(fixturePath, "export { expect, test } from '@playwright/test';\n");
}

test('Playwright client fixture uses the required non-empty destructured fixture argument', () => {
    const fixture = fs.readFileSync(path.join(templateRoot, 'tests/e2e/vertesia.ts'), 'utf8');

    assert.match(fixture, /vertesiaClient:\s*async \(\{ playwright: _playwright \}, use\) =>/);
    assert.doesNotMatch(fixture, /vertesiaClient:\s*async \(\{\}, use\) =>/);
    assert.doesNotMatch(fixture, /vertesiaClient:\s*async \(_fixtures, use\) =>/);
});

test('dev module codegen matches checked-in generated files', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['dev']);

        for (const file of generatedFiles) {
            const expected = fs.readFileSync(path.join(templateRoot, file), 'utf8');
            const actual = fs.readFileSync(path.join(tmpRoot, file), 'utf8');
            assert.equal(actual, expected, `${file} should match dev codegen output`);
        }
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('default module codegen keeps only the app module', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['default']);

        const uiModules = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-modules.tsx'), 'utf8');
        const serverModules = fs.readFileSync(path.join(tmpRoot, 'src/tool-server/app-server-modules.ts'), 'utf8');

        assert.match(uiModules, /modules\/app\/ui\/routes/);
        assert.doesNotMatch(uiModules, /modules\/assistant/);
        assert.doesNotMatch(uiModules, /modules\/examples/);
        assert.match(serverModules, /modules\/app\/resources\/index\.js/);
        assert.doesNotMatch(serverModules, /modules\/examples/);
        assert.match(serverModules, /export const hooks = \[\.\.\.appResources\.hooks\];/);
        assert.match(serverModules, /export const mcpProviders = \[\.\.\.appResources\.mcpProviders\];/);
        assert.match(serverModules, /export const subscriptions = \[\.\.\.appResources\.subscriptions\];/);
        const packageJson = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'package.json'), 'utf8'));
        assert.equal(packageJson.scripts['codegen:dev'], undefined);
        assert.equal(packageJson.scripts.pretest, undefined);
        assert.equal(packageJson.scripts['test:codegen'], undefined);
        assert.equal(packageJson.scripts.test, undefined);
        assert.equal(packageJson.scripts['test:unit'], undefined);
        assert.equal(packageJson.scripts['test:e2e'], undefined);
        assert.equal(packageJson.scripts['seed:content'], undefined);
        assert.equal(packageJson.scripts['exercise:content'], undefined);
        assert.equal(packageJson.scripts['service:quality'], undefined);
        assert.equal(packageJson.scripts['service:build'], undefined);

        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app/resources/hooks/index.ts')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app/resources/mcp/index.ts')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app/resources/subscriptions/index.ts')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/assistant')), false);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/examples')), false);
        const appRoutes = fs.readFileSync(path.join(tmpRoot, 'src/modules/app/ui/routes.tsx'), 'utf8');
        assert.doesNotMatch(appRoutes, /Document Library/);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app/resources/views/document-library.ts')), false);
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('appgen module selects the service entry and cleans inactive modules', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['appgen', 'assistant']);

        const uiEntry = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-entry.tsx'), 'utf8');
        const uiModules = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-modules.tsx'), 'utf8');
        const serverModules = fs.readFileSync(path.join(tmpRoot, 'src/tool-server/app-server-modules.ts'), 'utf8');
        const packageJson = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'package.json'), 'utf8'));

        assert.equal(uiEntry, `${generatedHeader}export { AppEntry } from '../modules/service/ui/AppEntry';\n`);
        assert.match(uiModules, /modules\/app\/ui\/routes/);
        assert.match(uiModules, /modules\/assistant\/ui\/routes/);
        assert.doesNotMatch(uiModules, /modules\/examples/);
        assert.match(serverModules, /modules\/app\/resources\/index\.js/);
        assert.doesNotMatch(serverModules, /modules\/examples/);
        assert.equal(packageJson.scripts['service:quality'], 'node src/modules/service/scripts/app-quality-check.mjs');
        assert.equal(packageJson.scripts.test, 'pnpm run test:unit');
        assert.equal(packageJson.scripts['test:unit'], 'vitest run src');
        assert.equal(packageJson.scripts['test:e2e'], 'playwright test');
        assert.equal(
            packageJson.scripts['service:build:server'],
            'pnpm run service:quality && node src/modules/service/scripts/build-server-esbuild.mjs && node src/modules/service/scripts/write-app-package.mjs',
        );
        assert.equal(
            packageJson.scripts['service:build:ui'],
            'pnpm run typecheck && vite build --mode app --outDir dist/app --emptyOutDir --minify false',
        );
        assert.equal(
            packageJson.scripts['service:build'],
            'pnpm run service:build:ui && vite build --mode lib && pnpm run service:build:server',
        );

        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/agent')), false);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/assistant')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/service')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/examples')), false);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app/ui/pages/HomePage.test.tsx')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'tests/e2e/app.spec.ts')), true);
        const appRoutes = fs.readFileSync(path.join(tmpRoot, 'src/modules/app/ui/routes.tsx'), 'utf8');
        const serviceEntry = fs.readFileSync(path.join(tmpRoot, 'src/modules/service/ui/AppEntry.tsx'), 'utf8');
        assert.doesNotMatch(appRoutes, /Document Library/);
        assert.match(serviceEntry, /client\.withAppVersion\(appVersion\)/);
        assert.doesNotMatch(serviceEntry, /useEffect/);
        assert.doesNotMatch(serviceEntry, /store\.withAppVersion/);
        execFileSync(process.execPath, ['src/modules/service/scripts/app-quality-check.mjs'], {
            cwd: tmpRoot,
            stdio: 'pipe',
            env: { ...process.env, APPGEN_REQUIRE_TESTS: '1' },
        });
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('appgen Playwright support keeps authenticated output safe and transient output ignored', () => {
    const playwrightConfig = fs.readFileSync(path.join(templateRoot, 'playwright.config.ts'), 'utf8');
    const playwrightFixture = fs.readFileSync(path.join(templateRoot, 'tests/e2e/vertesia.ts'), 'utf8');
    const serviceEntry = fs.readFileSync(path.join(templateRoot, 'src/modules/service/ui/AppEntry.tsx'), 'utf8');
    const gitignore = fs.readFileSync(path.join(templateRoot, '.gitignore'), 'utf8');

    assert.match(playwrightConfig, /VERTESIA_TOKEN/);
    assert.match(playwrightConfig, /hasVertesiaAuth \? 'off' : 'retain-on-failure'/);
    assert.match(playwrightFixture, /__VERTESIA_AUTH_TOKEN__/);
    assert.match(playwrightFixture, /headers\.authorization = `Bearer \$\{token\}`/);
    assert.match(playwrightFixture, /await VertesiaClient\.fromAuthToken/);
    assert.match(playwrightFixture, /PLAYWRIGHT_APP_VERSION/);
    assert.match(playwrightFixture, /client\.withAppVersion\(version\)/);
    assert.match(serviceEntry, /globalValues\.__VERTESIA_AUTH_TOKEN__/);
    assert.match(serviceEntry, /const runtimeAuthToken = injectedAuthToken \?\? devAuthToken/);
    assert.match(serviceEntry, /<VertesiaShell authToken=\{runtimeAuthToken\}>/);
    assert.match(gitignore, /pnpm-lock\.yaml/);
    assert.match(gitignore, /test-results\//);
    assert.match(gitignore, /playwright-report\//);
});

test('examples module contributes optional UI routes, views, hooks, and subscriptions', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['examples']);

        const uiModules = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-modules.tsx'), 'utf8');
        const serverModules = fs.readFileSync(path.join(tmpRoot, 'src/tool-server/app-server-modules.ts'), 'utf8');
        const appRoutes = fs.readFileSync(path.join(tmpRoot, 'src/modules/app/ui/routes.tsx'), 'utf8');
        const exampleRoutes = fs.readFileSync(path.join(tmpRoot, 'src/modules/examples/ui/routes.tsx'), 'utf8');
        const exampleResources = fs.readFileSync(
            path.join(tmpRoot, 'src/modules/examples/resources/views/index.ts'),
            'utf8',
        );
        const exampleHooks = fs.readFileSync(
            path.join(tmpRoot, 'src/modules/examples/resources/hooks/index.ts'),
            'utf8',
        );
        const exampleSubscriptions = fs.readFileSync(
            path.join(tmpRoot, 'src/modules/examples/resources/subscriptions/index.ts'),
            'utf8',
        );

        assert.match(uiModules, /modules\/examples\/ui\/routes/);
        assert.match(serverModules, /modules\/examples\/resources\/index\.js/);
        assert.doesNotMatch(appRoutes, /Document Library/);
        assert.match(exampleRoutes, /Document Library/);
        assert.match(exampleResources, /DocumentLibraryView/);
        assert.match(exampleHooks, /content-object-changed/);
        assert.match(exampleSubscriptions, /hook: 'content-object-changed'/);
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('service quality accepts an intentionally selected examples module', async () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['appgen', 'examples']);

        const packageJsonPath = path.join(tmpRoot, 'package.json');
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        packageJson.name = 'generated-examples-app';
        fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 4)}\n`);
        writeDurableTestFixtures(tmpRoot);

        const policyPath = path.join(tmpRoot, 'src/modules/service/scripts/template-example-policy.mjs');
        const { shouldRejectTemplateExampleIds } = await import(pathToFileURL(policyPath).href);
        assert.equal(shouldRejectTemplateExampleIds(packageJson.name, tmpRoot), false);

        execFileSync(process.execPath, ['src/modules/service/scripts/app-quality-check.mjs'], {
            cwd: tmpRoot,
            stdio: 'pipe',
            env: { ...process.env, APPGEN_REQUIRE_TESTS: '1' },
        });
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('service quality accepts every AppGen module selection', () => {
    const moduleSelections = [
        ['service'],
        ['service', 'assistant'],
        ['service', 'content-app'],
        ['service', 'examples'],
        ['service', 'assistant', 'content-app', 'examples'],
    ];

    for (const modules of moduleSelections) {
        const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
        try {
            copyTemplateInputs(tmpRoot);
            runCodegen(tmpRoot, modules);

            const packageJsonPath = path.join(tmpRoot, 'package.json');
            const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
            packageJson.name = `generated-${modules.join('-')}-app`;
            fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 4)}\n`);
            writeDurableTestFixtures(tmpRoot);

            execFileSync(process.execPath, ['src/modules/service/scripts/app-quality-check.mjs'], {
                cwd: tmpRoot,
                stdio: 'pipe',
                env: { ...process.env, APPGEN_REQUIRE_TESTS: '1' },
            });
        } catch (error) {
            assert.fail(`quality check failed for modules ${modules.join(', ')}: ${error}`);
        } finally {
            fs.rmSync(tmpRoot, { recursive: true, force: true });
        }
    }
});

test('service quality accepts the generated tests and rejects their removal', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['appgen']);
        const packageJsonPath = path.join(tmpRoot, 'package.json');
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        packageJson.name = 'generated-test-contract-app';
        fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 4)}\n`);

        const qualityScript = 'src/modules/service/scripts/app-quality-check.mjs';
        execFileSync(process.execPath, [qualityScript], {
            cwd: tmpRoot,
            stdio: 'pipe',
            env: { ...process.env, APPGEN_REQUIRE_TESTS: '1' },
        });
        let report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.equal(report.ok, true, 'a pristine generated AppGen repository must pass its required-test gate');
        assert.equal(
            Object.values(report.artifacts)
                .flat()
                .some((artifact) => /\.(?:test|spec)\.[cm]?[jt]sx?$/.test(artifact)),
            false,
            'test files must not be advertised as production artifacts',
        );

        fs.rmSync(path.join(tmpRoot, 'src/modules/app/ui/pages/HomePage.test.tsx'));
        fs.rmSync(path.join(tmpRoot, 'tests/e2e/app.spec.ts'));
        assert.throws(() =>
            execFileSync(process.execPath, [qualityScript], {
                cwd: tmpRoot,
                stdio: 'pipe',
                env: { ...process.env, APPGEN_REQUIRE_TESTS: '1' },
            }),
        );
        report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.deepEqual([...new Set(report.errors.map((error) => error.rule))].sort(), [
            'playwright-tests-required',
            'unit-tests-required',
        ]);

        writeDurableTestFixtures(tmpRoot);
        execFileSync(process.execPath, [qualityScript], {
            cwd: tmpRoot,
            stdio: 'pipe',
            env: { ...process.env, APPGEN_REQUIRE_TESTS: '1' },
        });
        report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.equal(report.ok, true);
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('service quality does not treat unit-test failure text as an end-user seed control', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['appgen']);
        const packageJsonPath = path.join(tmpRoot, 'package.json');
        const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
        packageJson.name = 'generated-seed-policy-app';
        fs.writeFileSync(packageJsonPath, `${JSON.stringify(packageJson, null, 4)}\n`);
        writeDurableTestFixtures(tmpRoot);

        const uiTestPath = path.join(tmpRoot, 'src/modules/app/ui/seed-contract.test.ts');
        fs.writeFileSync(
            uiTestPath,
            "import { expect, test } from 'vitest';\ntest('rejects stale data', () => expect(() => { throw new Error('stale seed marker'); }).toThrow());\n",
        );

        execFileSync(process.execPath, ['src/modules/service/scripts/app-quality-check.mjs'], {
            cwd: tmpRoot,
            stdio: 'pipe',
            env: { ...process.env, APPGEN_REQUIRE_TESTS: '1' },
        });
        const report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.equal(
            report.errors.some((error) => error.rule === 'no-end-user-seed-controls'),
            false,
        );
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('service quality rejects legacy Store search payloads and accepts ComplexSearchPayload', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['appgen']);
        const qualityScript = 'src/modules/service/scripts/app-quality-check.mjs';
        const seedPath = path.join(tmpRoot, 'scripts/seed-and-exercise.ts');
        fs.mkdirSync(path.dirname(seedPath), { recursive: true });
        fs.writeFileSync(
            seedPath,
            'await client.objects.search({ type: PROJECT_TYPE, query: SEED_PROJECT_NAME, limit: 5 });\n',
        );

        assert.throws(() => execFileSync(process.execPath, [qualityScript], { cwd: tmpRoot, stdio: 'pipe' }));
        let report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.equal(
            report.errors.some((error) => error.rule === 'valid-store-search-payload'),
            true,
        );

        fs.writeFileSync(
            seedPath,
            'const { results } = await client.objects.search({ query: { type: PROJECT_TYPE, name: SEED_PROJECT_NAME }, limit: 5 });\n',
        );
        execFileSync(process.execPath, [qualityScript], { cwd: tmpRoot, stdio: 'pipe' });
        report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.equal(
            report.errors.some((error) => error.rule === 'valid-store-search-payload'),
            false,
        );
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('service quality warns only for an actual TypeScript process definition', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        runCodegen(tmpRoot, ['appgen']);

        const qualityScript = 'src/modules/service/scripts/app-quality-check.mjs';
        execFileSync(process.execPath, [qualityScript], { cwd: tmpRoot, stdio: 'pipe' });
        let report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.equal(
            report.warnings.some((warning) => warning.rule === 'prefer-process-yaml'),
            false,
            'the generated empty processes/index.ts is not a process definition',
        );

        fs.writeFileSync(
            path.join(tmpRoot, 'src/modules/app/resources/processes/order-review.ts'),
            'export const OrderReview = { definition: { process: "order_review", nodes: {} } };\n',
        );
        execFileSync(process.execPath, [qualityScript], { cwd: tmpRoot, stdio: 'pipe' });
        report = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'dist/app-quality-report.json'), 'utf8'));
        assert.equal(
            report.warnings.some((warning) => warning.rule === 'prefer-process-yaml'),
            true,
            'a real TypeScript process definition should still recommend YAML source',
        );
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});

test('content-app module composes app routes and contributes resources', () => {
    const tmpRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'plugin-template-codegen-'));
    try {
        copyTemplateInputs(tmpRoot);
        writePackageJson(tmpRoot);
        runCodegen(tmpRoot, ['content-app']);

        const uiModules = fs.readFileSync(path.join(tmpRoot, 'src/ui/app-ui-modules.tsx'), 'utf8');
        const serverModules = fs.readFileSync(path.join(tmpRoot, 'src/tool-server/app-server-modules.ts'), 'utf8');
        const packageJson = JSON.parse(fs.readFileSync(path.join(tmpRoot, 'package.json'), 'utf8'));

        assert.match(uiModules, /modules\/app\/ui\/routes/);
        assert.match(uiModules, /modules\/content-app\/ui\/routes/);
        assert.match(serverModules, /modules\/app\/resources\/index\.js/);
        assert.match(serverModules, /modules\/content-app\/resources\/index\.js/);
        assert.match(serverModules, /export const dashboards = \[/);
        assert.match(serverModules, /export const processes = \[/);
        assert.equal(packageJson.scripts['seed:content'], 'node src/modules/content-app/scripts/seed-content-app.mjs');
        assert.equal(
            packageJson.scripts['exercise:content'],
            'node src/modules/content-app/scripts/exercise-content-app.mjs',
        );

        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/content-app')), true);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/assistant')), false);
        assert.equal(fs.existsSync(path.join(tmpRoot, 'src/modules/examples')), false);
    } finally {
        fs.rmSync(tmpRoot, { recursive: true, force: true });
    }
});
