export type ExperimentalAdmitAgentGenerationInitialPayload = Wire.ExperimentalAdmitAgentGenerationInitialPayload;
export type ExperimentalAdmitAgentGenerationPayload = Wire.ExperimentalAdmitAgentGenerationPayload;
export type ExperimentalAdmitAgentGenerationUserPayload = Wire.ExperimentalAdmitAgentGenerationUserPayload;
export type ExperimentalAdmitAgentGenerationToolsPayload = Wire.ExperimentalAdmitAgentGenerationToolsPayload;
export type ExperimentalAdmitAgentGenerationCheckpointPayload = Wire.ExperimentalAdmitAgentGenerationCheckpointPayload;

import type * as Wire from './wire-types.generated.js';

export type ExperimentalAgentRoutingIntent = Wire.ExperimentalAgentRoutingIntent;
export type ExperimentalAgentRoutingControlChange = Wire.ExperimentalAgentRoutingControlChange;
export type ExperimentalAgentRoutingControlBinding = Wire.ExperimentalAgentRoutingControlBinding;
export type ExperimentalUpdateAgentRoutingControlPayload = Wire.ExperimentalUpdateAgentRoutingControlPayload;
export type ExperimentalAgentRoutingControlReceipt = Wire.ExperimentalAgentRoutingControlReceipt;
export type ExperimentalAgentRoutingInitialReceipt = Wire.ExperimentalAgentRoutingInitialReceipt;
export type ExperimentalAgentRoutingChangeReceipt = Wire.ExperimentalAgentRoutingChangeReceipt;
export type ExperimentalAgentRoutingControlSelector = Wire.ExperimentalAgentRoutingControlSelector;
export type ExperimentalAgentRoutingControlQuery = Wire.ExperimentalAgentRoutingControlQuery;
export type ExperimentalAgentRoutingControlResponse = Wire.ExperimentalAgentRoutingControlResponse;

export type ExperimentalAgentRoutingOriginExecution = Wire.ExperimentalAgentRoutingOriginExecution;
export type ExperimentalAgentRoutingExecutionBinding = Wire.ExperimentalAgentRoutingExecutionBinding;
export type ExperimentalAgentGenerationAdmissionPayload = Wire.ExperimentalAgentGenerationAdmissionPayload;
export type ExperimentalAgentGenerationAdmissionReceipt = Wire.ExperimentalAgentGenerationAdmissionReceipt;
export type ExperimentalAgentRoutingStatusPayload = Wire.ExperimentalAgentRoutingStatusPayload;
export type ExperimentalAgentRoutingStatusResponse = Wire.ExperimentalAgentRoutingStatusResponse;
