import type * as Wire from './wire-types.generated.js';

export type ExperimentalCanonicalAsyncCompletionOptions = Wire.ExperimentalCanonicalAsyncCompletionOptions;
export type ExperimentalCanonicalResumeAccepted = Wire.ExperimentalCanonicalResumeAccepted;
export type ExperimentalCanonicalResumeTelemetry = Wire.ExperimentalCanonicalResumeTelemetry;
export type ExperimentalCanonicalToolResultsPayload = Wire.ExperimentalCanonicalToolResultsPayload;
export type ExperimentalCanonicalUserMessagePayload = Wire.ExperimentalCanonicalUserMessagePayload;

export type ExperimentalCanonicalResumeInputAppend = Wire.ExperimentalCanonicalResumeInputAppend;

export type ExperimentalCanonicalContinuationAnchor = Wire.ExperimentalCanonicalContinuationAnchor;

export type ExperimentalCanonicalCheckpointSummarySource = Wire.ExperimentalCanonicalCheckpointSummarySource;
export type ExperimentalCanonicalCheckpointSummaryPayload = Wire.ExperimentalCanonicalCheckpointSummaryPayload;
export type ExperimentalCanonicalUserMessageRequest = Wire.ExperimentalCanonicalUserMessageRequest;
