import type * as Wire from './wire-types.generated.js';

export type ExperimentalCanonicalInteractionInitialState = Wire.ExperimentalCanonicalInteractionInitialState;
export type ExperimentalCanonicalInteractionNewState = Wire.ExperimentalCanonicalInteractionNewState;
export type ExperimentalCanonicalInteractionDocumentState = Wire.ExperimentalCanonicalInteractionDocumentState;
export type ExperimentalCanonicalInteractionReferenceState = Wire.ExperimentalCanonicalInteractionReferenceState;
export type ExperimentalCanonicalInteractionConversationReference =
    Wire.ExperimentalCanonicalInteractionConversationReference;
export type ExperimentalCanonicalInteractionHeaders = Wire.ExperimentalCanonicalInteractionHeaders;
export type ExperimentalCanonicalInteractionRetrievalQuery = Wire.ExperimentalCanonicalInteractionRetrievalQuery;
export type ExperimentalCanonicalInteractionReturnPolicy = Wire.ExperimentalCanonicalInteractionReturnPolicy;
export type ExperimentalCanonicalInteractionAutoTurnSelection = Wire.ExperimentalCanonicalInteractionAutoTurnSelection;
export type ExperimentalCanonicalInteractionNoneTurnSelection = Wire.ExperimentalCanonicalInteractionNoneTurnSelection;
export type ExperimentalCanonicalInteractionRequiredTurnSelection =
    Wire.ExperimentalCanonicalInteractionRequiredTurnSelection;
export type ExperimentalCanonicalInteractionTurnSelection = Wire.ExperimentalCanonicalInteractionTurnSelection;
export type ExperimentalCanonicalInteractionExecutionConfiguration =
    Wire.ExperimentalCanonicalInteractionExecutionConfiguration;
export type ExperimentalCanonicalInteractionResultSchemaInput = Wire.ExperimentalCanonicalInteractionResultSchemaInput;
export type ExperimentalCanonicalInteractionInlinePrompt = Wire.ExperimentalCanonicalInteractionInlinePrompt;
export type ExperimentalCanonicalInteractionExecutionRequest = Wire.ExperimentalCanonicalInteractionExecutionRequest;
export type ExperimentalCanonicalNamedInteractionExecutionRequest =
    Wire.ExperimentalCanonicalNamedInteractionExecutionRequest;
export type ExperimentalCanonicalInteractionModelSwitchBinding =
    Wire.ExperimentalCanonicalInteractionModelSwitchBinding;
export type ExperimentalCanonicalInteractionModelSwitchPrepareRequest =
    Wire.ExperimentalCanonicalInteractionModelSwitchPrepareRequest;
export type ExperimentalCanonicalInteractionModelSwitchPrepareResult =
    Wire.ExperimentalCanonicalInteractionModelSwitchPrepareResult;
export type ExperimentalCanonicalInteractionDocumentHistory = Wire.ExperimentalCanonicalInteractionDocumentHistory;
export type ExperimentalCanonicalInteractionReferenceHistory = Wire.ExperimentalCanonicalInteractionReferenceHistory;
export type ExperimentalCanonicalInteractionUnavailableHistory =
    Wire.ExperimentalCanonicalInteractionUnavailableHistory;
export type ExperimentalCanonicalInteractionHistory = Wire.ExperimentalCanonicalInteractionHistory;
export type ExperimentalCanonicalInteractionRun = Wire.ExperimentalCanonicalInteractionRun;
export type ExperimentalCanonicalInteractionAcceptedOutput = Wire.ExperimentalCanonicalInteractionAcceptedOutput;
export type ExperimentalCanonicalInteractionUnavailableOutput = Wire.ExperimentalCanonicalInteractionUnavailableOutput;
export type ExperimentalCanonicalInteractionOutput = Wire.ExperimentalCanonicalInteractionOutput;
export type ExperimentalCanonicalInteractionExecutionResult = Wire.ExperimentalCanonicalInteractionExecutionResult;

export type ExperimentalCanonicalVirtualGenerationBinding = Wire.ExperimentalCanonicalVirtualGenerationBinding;
