import type * as Wire from './wire-types.generated.js';

export type AppendRunConversationProgramTurnPayload = Wire.AppendRunConversationProgramTurnPayload;
export type AppendRunConversationProgramTurnResponse = Wire.AppendRunConversationProgramTurnResponse;
export type AppendRunConversationToolResultsPayload = Wire.AppendRunConversationToolResultsPayload;
export type AppendRunConversationToolResultsResponse = Wire.AppendRunConversationToolResultsResponse;
export type PublishAgentRunConversationHeadPayload = Wire.PublishAgentRunConversationHeadPayload;
export type ExperimentalAgentProcessingHeadPayload = Wire.ExperimentalAgentProcessingHeadPayload;
export type ExperimentalCanonicalVersionedHeadPayload = Wire.ExperimentalCanonicalVersionedHeadPayload;

export type ExperimentalCanonicalInitialRenderedInputHeadPayload =
    Wire.ExperimentalCanonicalInitialRenderedInputHeadPayload;

export type ExperimentalCanonicalToolCatalogSelectionHeadPayload =
    Wire.ExperimentalCanonicalToolCatalogSelectionHeadPayload;
