/**
 * Emits a narrow browser-safe validator for the experimental canonical interaction stream wire boundary.
 * The input schemas come from the same generated component closure published in OpenAPI; this file contains no
 * independently authored wire rules.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { Ajv2020 } from 'ajv/dist/2020.js';
import standaloneCode from 'ajv/dist/standalone/index.js';
import { bundleCanonicalComponent } from '../src/api-contract/index.js';

const output = fileURLToPath(
    new URL('../src/canonical-stream-runtime/canonical-stream-validator.generated.js', import.meta.url),
);
const componentNames = [
    'ConversationStreamIdentity',
    'ConversationStreamCursor',
    'ConversationStreamEvent',
    'ExperimentalCanonicalInteractionStreamEnvelope',
    'ExperimentalAgentConversationStreamEnvelope',
    'ExperimentalAgentEditingResource',
    'ExperimentalAgentDocumentEditingAction',
    'ExperimentalAgentUserInputMetadata',
    'ExperimentalAgentRunControlEvent',
    'ExperimentalAgentRunStreamEnvelope',
    'ExperimentalAgentRunUpdatesResponse',
    'ExperimentalAgentConversationTranscriptPage',
    'ExperimentalAgentConversationSourceDescriptor',
] as const;

const definitions: Record<string, unknown> = {};
for (const name of componentNames) {
    const bundled = bundleCanonicalComponent(name);
    const { $defs, ...component } = bundled;
    Object.assign(definitions, ($defs ?? {}) as Record<string, unknown>);
    definitions[name] = component;
}

const selectorSchema = {
    $defs: definitions,
    oneOf: componentNames.map((name) => ({
        type: 'object',
        properties: {
            kind: { const: name },
            value: { $ref: `#/$defs/${name}` },
        },
        required: ['kind', 'value'],
        additionalProperties: false,
    })),
};

const ajv = new Ajv2020({ strict: false, allErrors: false, code: { source: true, esm: true } });
const validate = ajv.compile(selectorSchema);
let generated = standaloneCode(ajv, validate);
generated = generated.replace(
    '"use strict";',
    `function canonicalStreamUcs2Length(value) {
    let length = 0;
    for (let index = 0; index < value.length; index += 1) {
        const codeUnit = value.charCodeAt(index);
        if (codeUnit >= 0xd800 && codeUnit <= 0xdbff && index + 1 < value.length) {
            const low = value.charCodeAt(index + 1);
            if ((low & 0xfc00) === 0xdc00) index += 1;
        }
        length += 1;
    }
    return length;
}`,
);
generated = generated.replace(
    /const (func\d+) = require\("ajv\/dist\/runtime\/ucs2length"\)\.default;/g,
    'const $1 = canonicalStreamUcs2Length;',
);
if (generated.includes('require(')) {
    throw new Error('Canonical stream standalone validator contains a non-ESM runtime dependency');
}

writeFileSync(
    output,
    `// Generated by scripts/gen-canonical-stream-validator.ts from the canonical API component closure.\n${generated}\n`,
);
console.log(`Wrote canonical stream standalone validator to ${output}`);
