import { log } from "@temporalio/activity";
import { ContentObjectStatus, DSLActivityExecutionPayload, DSLActivitySpec } from "@vertesia/common";
import { setupActivity } from "../../dsl/setup/ActivityContext.js";
import { ActivityParamNotFoundError, DocumentNotFoundError } from "../../errors.js";

interface CreateOrUpdateObjectFromInteractionRunParams {
    /**
     * The execution run object to use. Required.
     * Not required in params since it is usually fetched
     */
    run_id?: string,
    /**
     * The document type to use. Required if update_existing_id is false.
     * Not required in params since it is usually fetched
     */
    object_type?: string,

    /**
     * The id of the document to update. If not provided, a new document will be created
     */
    update_existing_id?: string,

    /**
     * The name of the object to use. If not provided, the name will be generated from the interaction result
     */
    fallback_name?: string, // a name to use if no one was generated by the interaction

    /**
     * The name of the parent object to use. If not provided, the document will be created at the root level
     */
    parent?: string, // the parent object id

    /**
     * The name of the property to use for the text. If not provided, the text will be set to the result of the interaction
     */
    update_text_from_property?: string,

}

export interface CreateOrUpdateObjectFromInteractionRun extends DSLActivitySpec<CreateOrUpdateObjectFromInteractionRunParams> {
    name: 'createOrUpdateDocumentFromInteractionRun';
}

export async function createOrUpdateDocumentFromInteractionRun(payload: DSLActivityExecutionPayload<CreateOrUpdateObjectFromInteractionRunParams>) {
    const { params, client } = await setupActivity<CreateOrUpdateObjectFromInteractionRunParams>(payload);

    const runId = params.run_id;
    const objectTypeName = params.object_type;

    if (!runId) {
        throw new ActivityParamNotFoundError("run_id", payload.activity);
    }
    if (!objectTypeName && !params.update_existing_id) {
        throw new ActivityParamNotFoundError("object_type", payload.activity);
    }

    log.info("Creating document from interaction result", { runId, objectTypeName });

    const run = await client.runs.retrieve(runId).catch((e) => {
        throw new DocumentNotFoundError(`Error fetching run ${runId}: ${e.message}`);
    });

    const type = objectTypeName ?
        await client.types.getTypeByName(objectTypeName).catch((e) => {
            throw new DocumentNotFoundError(`Error fetching type ${objectTypeName}: ${e.message}`);
        })
        : undefined;


    const result = run.result;
    const inputData = run.parameters;

    // Try to parse result as JSON, fallback to text if not valid JSON
    let jsonResult: any = null;
    try {
        jsonResult = result.object();
    } catch (e) {
        log.info("Result is not valid JSON, will use text content instead", { error: e instanceof Error ? e.message : String(e) });
    }

    const name = jsonResult?.['name'] || jsonResult?.["title"] || inputData['name'] || params.fallback_name || undefined;

    const docPayload = {
        name,
        parent: params.parent ?? undefined,
        properties: jsonResult ? jsonResult : {},
        text: !jsonResult ? result.text() : undefined,
        type: type?.id,
        status: ContentObjectStatus.completed,
        generation_run_info: {
            id: run.id,
            date: new Date().toISOString(),
            model: run.modelId ?? "",
            target: jsonResult ? 'properties' : 'text'
        }
    };

    if (params.update_text_from_property) {
        const text = docPayload.properties[params.update_text_from_property];
        if (text) {
            docPayload.text = text;
        }
    }

    //create or update the document
    let newDoc: boolean = false;
    let doc = undefined;
    if (params.update_existing_id) {
        log.info(`Updating existing document ${params.update_existing_id}`);
        doc = await client.objects.update(params.update_existing_id, docPayload, { suppressWorkflows: true });
    } else {
        log.info(`Creating new document of type ${objectTypeName}`);
        doc = await client.objects.create(docPayload);
        newDoc = true;
    }

    log.info(`Document ${objectTypeName + ' '}${doc.id}(${doc.name}) ${newDoc ? 'created' : 'updated'}`);
    return { id: doc.id, isNew: newDoc, type: name }
}
