import { log } from '@temporalio/activity';
import {
    type ContentObject,
    ContentObjectStatus,
    type DSLActivityExecutionPayload,
    type DSLActivitySpec,
    type JSONObject,
} from '@vertesia/common';
import { setupActivity } from '../../dsl/setup/ActivityContext.js';
import { ActivityParamNotFoundError, DocumentNotFoundError } from '../../errors.js';
import { requireCanonicalInteractionOutput } from '../executeInteraction.js';

interface CreateOrUpdateObjectFromInteractionRunParams {
    /**
     * The execution run object to use. Required.
     * Not required in params since it is usually fetched
     */
    run_id?: string;
    /**
     * The document type to use. Required if update_existing_id is false.
     * Not required in params since it is usually fetched
     */
    object_type?: string;

    /**
     * The id of the document to update. If not provided, a new document will be created
     */
    update_existing_id?: string;

    /**
     * The name of the object to use. If not provided, the name will be generated from the interaction result
     */
    fallback_name?: string; // a name to use if no one was generated by the interaction

    /**
     * The name of the parent object to use. If not provided, the document will be created at the root level
     */
    parent?: string; // the parent object id

    /**
     * The name of the property to use for the text. If not provided, the text will be set to the result of the interaction
     */
    update_text_from_property?: string;
}

export interface CreateOrUpdateObjectFromInteractionRun
    extends DSLActivitySpec<CreateOrUpdateObjectFromInteractionRunParams> {
    name: 'createOrUpdateDocumentFromInteractionRun';
}

interface InteractionRunDocumentSource {
    id: string;
    inputName?: string;
    jsonResult: JSONObject | null;
    modelId: string;
    recordedAt: string;
    textResult?: string;
}

function objectResult(value: unknown, runId: string): JSONObject {
    if (value === null || typeof value !== 'object' || Array.isArray(value)) {
        throw new Error(`Canonical run ${runId} produced a non-object JSON output`);
    }
    return value as JSONObject;
}

async function loadOptionalInputName(
    client: Awaited<ReturnType<typeof setupActivity>>['client'],
    runId: string,
): Promise<string | undefined> {
    try {
        const run = await client.runs.retrieve<unknown, Record<string, unknown>>(runId);
        return typeof run.parameters.name === 'string' ? run.parameters.name : undefined;
    } catch (error: unknown) {
        // Canonical output remains authoritative and sufficient under restricted retention. The
        // host projection is consulted only for the optional input name retained by this reusable
        // activity's legacy naming behavior.
        log.debug('Interaction input name metadata is unavailable', {
            runId,
            error: error instanceof Error ? error.message : String(error),
        });
        return undefined;
    }
}

function errorStatus(error: unknown): number | undefined {
    if (error === null || typeof error !== 'object') return undefined;
    const status = 'status' in error ? error.status : 'statusCode' in error ? error.statusCode : undefined;
    return typeof status === 'number' ? status : undefined;
}

async function loadLegacyRunSource(
    client: Awaited<ReturnType<typeof setupActivity>>['client'],
    runId: string,
): Promise<InteractionRunDocumentSource> {
    const run = await client.runs
        .retrieve<Record<string, unknown>, Record<string, unknown>>(runId)
        .catch((error: unknown) => {
            const message = error instanceof Error ? error.message : String(error);
            throw new DocumentNotFoundError(`Error fetching run ${runId}: ${message}`);
        });

    let jsonResult: JSONObject | null = null;
    try {
        jsonResult = run.result.object<JSONObject>();
    } catch (error: unknown) {
        log.debug('Result is not valid JSON, will use text content instead', {
            error: error instanceof Error ? error.message : String(error),
        });
    }
    return {
        id: run.id,
        inputName: typeof run.parameters.name === 'string' ? run.parameters.name : undefined,
        jsonResult,
        modelId: run.modelId ?? '',
        recordedAt: new Date().toISOString(),
        textResult: jsonResult ? undefined : run.result.text(),
    };
}

async function loadRunSource(
    client: Awaited<ReturnType<typeof setupActivity>>['client'],
    runId: string,
): Promise<InteractionRunDocumentSource> {
    let canonical: Awaited<ReturnType<typeof client.runs.retrieveCanonical>>;
    try {
        canonical = await client.runs.retrieveCanonical<JSONObject>(runId);
    } catch (error: unknown) {
        // A pre-canonical Studio host has no versioned retrieval route. Preserve the old activity
        // boundary during a mixed-version rollout; other failures remain visible and retryable.
        if (errorStatus(error) === 404) return loadLegacyRunSource(client, runId);
        throw error;
    }
    if (canonical.output.status !== 'accepted') {
        // Runs created before canonical output persistence are explicitly reported as not_recorded.
        // That is the sole stored-result compatibility case; a missing/pruned accepted result from
        // a canonical run must not be silently replaced by a weaker legacy projection.
        if (canonical.output.reason === 'not_recorded') return loadLegacyRunSource(client, runId);
        throw new DocumentNotFoundError(`Canonical output for run ${runId} is unavailable: ${canonical.output.reason}`);
    }

    const output = requireCanonicalInteractionOutput(canonical);
    const generation = output.fragment.generation;
    const turn = output.fragment.turn;
    if (generation.status !== 'completed' || turn.status !== 'completed') {
        throw new DocumentNotFoundError(
            `Canonical output for run ${runId} is not completed: generation=${generation.status}, turn=${turn.status}`,
        );
    }
    const unsupportedBlock = output.blocks.find(
        (block) => block.type !== 'json' && block.type !== 'text' && block.type !== 'reasoning',
    );
    if (unsupportedBlock) {
        throw new Error(`Canonical ${unsupportedBlock.type} output cannot update a content object`);
    }
    const objects = output.objects<unknown>();
    if (objects.length > 1) {
        throw new Error(`Canonical run ${runId} produced multiple JSON outputs`);
    }
    const jsonResult = objects[0] === undefined ? null : objectResult(objects[0], runId);
    return {
        id: canonical.run.id,
        inputName: await loadOptionalInputName(client, runId),
        jsonResult,
        modelId: generation.resolved_model ?? generation.requested_model,
        recordedAt: generation.timestamps.recorded_at,
        textResult: jsonResult ? undefined : output.text(),
    };
}

export async function createOrUpdateDocumentFromInteractionRun(
    payload: DSLActivityExecutionPayload<CreateOrUpdateObjectFromInteractionRunParams>,
) {
    const { params, client } = await setupActivity<CreateOrUpdateObjectFromInteractionRunParams>(payload);

    const runId = params.run_id;
    const objectTypeName = params.object_type;

    if (!runId) {
        throw new ActivityParamNotFoundError('run_id', payload.activity);
    }
    if (!objectTypeName && !params.update_existing_id) {
        throw new ActivityParamNotFoundError('object_type', payload.activity);
    }

    log.debug('Creating document from interaction result', { runId, objectTypeName });

    const run = await loadRunSource(client, runId);

    const type = objectTypeName
        ? await client.types.getTypeByName(objectTypeName).catch((e: unknown) => {
              const message = e instanceof Error ? e.message : String(e);
              throw new DocumentNotFoundError(`Error fetching type ${objectTypeName}: ${message}`);
          })
        : undefined;

    const { inputName, jsonResult } = run;

    const nameValue = jsonResult?.name || jsonResult?.title || inputName || params.fallback_name || undefined;
    const name = typeof nameValue === 'string' ? nameValue : undefined;

    // An interaction with no result schema returns prose, which belongs in `text`. Sending
    // `properties: {}` in that case is not a no-op: the store treats a present `properties` as a
    // full replacement, so it would erase whatever the object already carried (and clear the
    // derived embeddings with it). Omit the field entirely unless the run produced JSON.
    const target: 'properties' | 'text' = jsonResult ? 'properties' : 'text';
    const docPayload: {
        name?: string;
        parent?: string;
        properties?: JSONObject;
        text?: string;
        type?: string;
        status: ContentObjectStatus;
        generation_run_info: { id: string; date: string; model: string; target: string };
    } = {
        name,
        parent: params.parent ?? undefined,
        properties: jsonResult ?? undefined,
        text: run.textResult,
        type: type?.id,
        status: ContentObjectStatus.completed,
        generation_run_info: {
            id: run.id,
            date: run.recordedAt,
            model: run.modelId,
            target,
        },
    };

    if (params.update_text_from_property) {
        const text = docPayload.properties?.[params.update_text_from_property];
        if (typeof text === 'string') {
            docPayload.text = text;
        }
    }

    //create or update the document
    let newDoc: boolean = false;
    let doc: ContentObject;
    if (params.update_existing_id) {
        log.debug(`Updating existing document ${params.update_existing_id}`);
        doc = await client.objects.update(params.update_existing_id, docPayload, { suppressWorkflows: true });
    } else {
        log.debug(`Creating new document of type ${objectTypeName}`);
        doc = await client.objects.create(docPayload);
        newDoc = true;
    }

    log.debug(`Document ${`${objectTypeName} `}${doc.id}(${doc.name}) ${newDoc ? 'created' : 'updated'}`);
    // `target` tells the caller which field the run actually populated. Media intake needs it to know
    // whether properties were written or whether it still has to run its own extraction pass.
    return { id: doc.id, isNew: newDoc, type: name, target };
}
