name: publish-npm-dev-packages

on:
  workflow_dispatch:
    inputs: {}

permissions:
  id-token: write  # Required for OIDC between GitHub and NPM
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - name: Publish packages to NPM
        run: |
          set +x
          current_version=$(pnpm pkg get version | tr -d '"')
          dev_version="${current_version}-dev-${GITHUB_SHA::7}"
          pnpm -r --filter "./packages/*" exec npm version ${dev_version} --no-git-tag-version
          pnpm -r --filter "./packages/*" exec npm publish --access public --tag dev
