name: publish-npm-dev-packages

on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - run: pnpm install
      - name: Change version
        run: |
          set +x
          CURRENT_VERSION=$(pnpm pkg get version | tr -d '"')
          DEV_VERSION="${CURRENT_VERSION}-dev-${GITHUB_SHA::7}"
          pnpm version ${DEV_VERSION} --recursive --no-git-tag-version
          pnpm publish --recursive --tag dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
