name: publish-npm-dev-packages

on:
  workflow_dispatch:
    inputs: {}

permissions:
  id-token: write  # Required for OIDC between GitHub and NPM
  contents: read

jobs:
  publish:
    name: publish-${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - common
          - converters
          # TODO: add more packages when tests passed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          cache: "pnpm"

      - run: npm --version
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm --version

      - run: pnpm install
      - name: Publish packages to NPM
        run: |
          set +x
          current_version=$(pnpm pkg get version | tr -d '"')
          dev_version="${current_version}-dev-${GITHUB_SHA::7}"
          echo "Changing version from [${current_version}] to [${dev_version}]"

          pnpm -r --filter "./packages/*" exec npm version ${dev_version} --no-git-tag-version

          cd "packages/${{ matrix.package }}"
          # --no-git-checks: don't check whenther the working directory is clean because we update
          #     the version directly in the CI
          npm --prefix  publish --access public --tag dev --no-git-checks
